
package com.snitsar.forecast.current;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CurrentWeatherForOneLocationService", targetNamespace = "http://current.forecast.snitsar.com/", wsdlLocation = "http://localhost:8082/current?wsdl")
public class CurrentWeatherForOneLocationService
    extends Service
{

    private final static URL CURRENTWEATHERFORONELOCATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CURRENTWEATHERFORONELOCATIONSERVICE_EXCEPTION;
    private final static QName CURRENTWEATHERFORONELOCATIONSERVICE_QNAME = new QName("http://current.forecast.snitsar.com/", "CurrentWeatherForOneLocationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/current?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURRENTWEATHERFORONELOCATIONSERVICE_WSDL_LOCATION = url;
        CURRENTWEATHERFORONELOCATIONSERVICE_EXCEPTION = e;
    }

    public CurrentWeatherForOneLocationService() {
        super(__getWsdlLocation(), CURRENTWEATHERFORONELOCATIONSERVICE_QNAME);
    }

    public CurrentWeatherForOneLocationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURRENTWEATHERFORONELOCATIONSERVICE_QNAME, features);
    }

    public CurrentWeatherForOneLocationService(URL wsdlLocation) {
        super(wsdlLocation, CURRENTWEATHERFORONELOCATIONSERVICE_QNAME);
    }

    public CurrentWeatherForOneLocationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURRENTWEATHERFORONELOCATIONSERVICE_QNAME, features);
    }

    public CurrentWeatherForOneLocationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrentWeatherForOneLocationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CurrentWeatherForOneLocation
     */
    @WebEndpoint(name = "CurrentWeatherForOneLocationPort")
    public CurrentWeatherForOneLocation getCurrentWeatherForOneLocationPort() {
        return super.getPort(new QName("http://current.forecast.snitsar.com/", "CurrentWeatherForOneLocationPort"), CurrentWeatherForOneLocation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrentWeatherForOneLocation
     */
    @WebEndpoint(name = "CurrentWeatherForOneLocationPort")
    public CurrentWeatherForOneLocation getCurrentWeatherForOneLocationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://current.forecast.snitsar.com/", "CurrentWeatherForOneLocationPort"), CurrentWeatherForOneLocation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURRENTWEATHERFORONELOCATIONSERVICE_EXCEPTION!= null) {
            throw CURRENTWEATHERFORONELOCATIONSERVICE_EXCEPTION;
        }
        return CURRENTWEATHERFORONELOCATIONSERVICE_WSDL_LOCATION;
    }

}
